server:
  rest_port: 8090
  grpc_port: 9090

postgres:
  host:     postgres
  port:     5432
  user:     auth
  password: authpass
  dbname:   auth
  sslmode:  disable

redis:
  addr: "redis:6379"
  db:   0

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"

keycloak:
  url:      "http://keycloak:8080"
  realm:    "auth-realm"
  client_id: "backend"
  secret:   "UUTSQCSZpGRI4xB6l5yPjmfp0TnmgWII"

jwt:
  signing_key: "your-very-secure-signing-key"
  ttl:         "15m"

email:
  from: "noreply@myapp.io"
  smtp_host: "smtp.mailgun.org"
  smtp_port: 587
  smtp_user: "postmaster@myapp.io"
  smtp_pass: "${SMTP_PASS}"
  use_tls: false
  dial_timeout: "5s"
  confirmation_ttl: "24h"

logstash:
  tcp_addr: "logstash:5000"
